server:
  port: 9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  #网关也是个微服务，需要注册到服务注册发现中心
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: cloud-gateway-service

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment-routh                 #路由的ID，没有固定规则但要求唯一
          #uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**          #断言，路径相匹配的进行路由
          filters:
            - AddRequestParameter=X-Request-Id, 1024 #过滤器工厂会在匹配的请求上加上请求头，名称为X-Request-Id， 值为1024
        - id: payment-routh2                #路由的ID，没有固定规则但要求唯一
          #uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #在这个微服务集群进行负载均衡的调用
          predicates:
            - Path=/payment/lb/**           #断言，路径相匹配的进行路由
      discovery:
        locator:
          enabled:  true                    #开启从注册中心动态创建路由的功能，利用微服务名字进行路由